import React, { useState } from "react";
import Select from "react-select";
import "./Form.css";
import { useNavigate } from "react-router-dom";

const productOptions = [
  "Potting Mix for Plants (2.150kg)",
"Muskmelon Seeds (3 seeds)",
"Carrot Seeds (10 seeds)",
"Broccoli Seeds (20 seeds)",
"Pumpkin Seeds (5 seeds)",
"Brinjal Seeds (12 seeds)",
"Vincarosa Mixed Seeds (30 seeds)",
"Cosmos Mixed Sensation Seeds (20 seeds)",
"Daisy Mixed Seeds (30 seeds)",
"Onion Seeds (20 seeds)",
"Lettuce Seeds (10 seeds)",
"Stocks Mixed Seeds (15 seeds)",
"Venidium Orange Seeds (20 seeds)",
"Portulaca Mixed Seeds (100seeds)",
"Holly Hock Seeds (5 seeds)",
"Zinnia White Seeds (6 seeds)",
"Papaya Seeds (3 seeds)",
"Mint Seeds (30 Seeds)",
"Oregano Seeds (30 seeds)",
"Dahlia Mixed Seeds (20 seeds)",
"French Orange Marigold Seeds (10 seeds)",
"Spring Onion Seeds (10 seeds)",
"Strawberry Seeds (25 Seeds)",
"Balsam Seeds (20 seeds)",
"Poppy Double Mix Seeds (30 seeds)",
"Cucumber Seeds (5 Seeds)",
"Watermelon Seeds (3 seeds)",
"Kale Seeds (10 seeds)",
"Cockscomb Mixed Seeds (30 Seeds)",
"Morning Glory Seeds (5 seeds)",
"Salvia Red Seeds (10 seeds)",
"Calendula Pacific Beauty Seeds (10 seeds)",
"Larkspur Mixed Seeds (10 seeds)",
"Cherry Tomato Seeds (25 seeds)",
"Cosmos Orange Seeds (10 seeds)",
"Zinnia Pink Seeds (6 seeds)",
"Zinnia Yellow Seeds (10 seeds)",
"Asparagus Seeds (5 seeds)",
"Neem Cake Powder for Plants (10gms)",
"Epsom Salt for Plants (20gms)",
"Trowel/ Spade/ Desi Khurpa (Gardening Tool)",
"Amaranthus Red Seeds (10 seeds)",
"Candytuft Seeds (10 seeds)",
"Coreopsis Beauty Star Mix Seeds (10 seeds)",
"Parsley Seeds (10 seeds)",
"Sweet Corn Seeds (4 seeds)",
"Rudbeckia Seeds (20 seeds)",
"Sweet Pea Seeds (5 seeds)",
"Baby Corn Seeds (3 Seeds)",
"Tar Kakri Seeds (5 seeds)",
"Neem Oil (30ml)",
"Cleome Spinosa Seeds (10 seeds)",
"Cosmos Yellow Seeds (20 seeds)",
"Poppy Iceland Mix Seeds (30 seeds)",
"Gardening Tools Set (Cultivator, Small Trowel &amp; Gardening Fork)",
"Beginner's Veggies Seeds Pack (1Pack)",
"Cow Dung Dhoop- Sambarani (1pc)",
"Demand Agro Kale Curly Seeds",
"15ml Glass Bottle with Cork",
"5ml Glass Bottle with Cork",
"Alyssum Snow White Seeds (50 seeds)",
"Amaranthus Tricolor Seeds (30 seeds)",
"Antirrhinum Double Mixed Seeds (30 seeds)",
"Aster Mixed Seeds (10 Seeds)",
"Bamboo Toothbrush",
"Basil Green Seeds (20 seeds)",
"Beans Seeds (10 seeds)",
"Beginner's Basic Garden Kit (1Kit)",
"Beginner's Elite Garden Kit (1Kit)",
"Big Grow Bag (12*12 inch)",
"Bitter Gourd Seeds (5 seeds)",
"Bottle Gourd Seeds (3 seeds)",
"Capsicum Green Seeds (10 seeds)",
"Capsicum Red Seeds (10 seeds)",
"Carnation Seeds (20 seeds)",
"Moringa Seeds (Drumsticks) (3 seeds)",
"Dimorphotheca Seeds (5 seeds)",
"Sunflower Tall Seeds (20 seeds)",
"Pea Seeds (5 Seeds)",
"Cluster Beans Seeds (3 seeds)",
"Medium Size Pot Saucer (1pc)",
"Holy Basil/ Tulsi Seeds (20 seeds)",
"Gaillardia Seeds (10 seeds)",
"Verbena Mixed Seeds (10 seeds)",
"Lupins Mixed Seeds (10 seeds)",
"Epsom Salt (250gms)",
"Phlox Mixed Seeds (20 seeds)",
"Gompherena Mixed Seeds (10 seeds)",
"Turnip Purple Top Seeds (5 seeds)",
"Cauliflower Seeds (10 seeds)",
"Petunia Mixed Seeds (30 seeds)",
"German Chamomile Seeds (30 seeds)",
"Red Hibiscus Seeds (5 Seeds)",
"Zinnia Double Mix Seeds (30 seeds)",
"Kochia Seeds (40 seeds)",
"Vermi Compost Single Serve (10 gms)",
"Italian Acrylic Cosmetic Jars with Clear Cap (1pc)",
"Poppy California Seeds (10 seeds)",
"Desi Mosquito Repellent Cow Dung Cake (1+1)",
"Perlite Soil (5gms)",
"Nemesis Mixed Seeds (20seeds)",
"Small Cute Glass Jars",
"Gypsophila Seeds (10 seeds)",
"Plant Tag Ice Cream Sticks (5 Sticks)",
"Mesembryanthemum Seeds (30seeds)",
"Marigold French Scarlet Red Seeds (10seeds)",
"Sweet Sultan Seeds (5seeds)",
"Clarkia Double Mix Seeds (30seeds)",
"Lemon Grass Seeds (30seeds)",
"Cow Dung Powder (100gms)",
"Long Brinjal Seeds (10seeds)",
"Mini 30ml Portable Spray Bottle",
"Mosquito Repellent Cow Dung Diya Small (1pc)",
"Wheatgrass Seeds (10gms)",
"Cherry Tomato &amp; Basil Pizza Seeds Pack (1 Pack)",
"Winter Veggies Seeds Pack (1Pack)",
"Pot Meal Pack (1Pack)",
"Wedding Flowers Seeds Pack (1Pack)",
"Easy to Grow Flowers Seeds Pack (1Pack)",
"Dhania Mirchi Seeds Pack (1Pack)",
"Salad Seeds Pack (1Pack)",
"Daily Essential Veggies Seeds Pack (1Pack)",
"Puja Seeds Pack (1Pack)",
"Demand Agro Basil Green Seeds",
"Demand Agro Broccoli F1 Green Giant Seeds",
"Demand Agro Capsicum F1 Coloured Seeds",
"Demand Agro Celery Seeds",
"Demand Agro Ashwagandha Seeds",
"Demand Agro Chinese Cabbage F1 Hybrid Seeds",
"Demand Agro Dill Seeds (100seeds)",
"Demand Agro Knol Khol Seeds",
"Demand Agro Leak Lenceolot Seeds",
"Demand Agro Lemon Grass Seeds",
"Demand Agro Lettuce Angelina Seeds",
"Demand Agro Lettuce Iceberg Seeds",
"Demand Agro Lettuce Red Grande Seeds (275seeds)",
"Demand Agro Oregano Seeds",
"Demand Agro Parsley F1 Hybrid Seeds",
"Demand Agro Red Cabbage F1 Hybrid Seeds",
"Demand Agro Rocket Seeds (150seeds)",
"Demand Agro Rosemary Seeds",
"Demand Agro Stevia Seeds",
"Demand Agro Thyme Seeds (70 seeds)",
"HydroGel (For vacation watering, 20gms)",
"Demand Agro Aster Double Mix Seeds",
"Demand Agro Gaillardia Aristata Mixed Seeds",
"Lavender Seeds (100 seeds)",
"White Onion Seeds (10 Seeds)",
"Thyme Seeds (30 Seeds)",
"Microgreen Mustard Seeds (10 gms)",
"Microgreen Sesame Seeds (10 gms)",
"Microgreen Sunflower Seeds (10 gms)",
"Crystal Soil balls (50 pcs)",
"Wisitiria Strawberry Seeds (100 seeds)",
"Wisitiria Lemon Grass Seeds (50 seeds)",
"Wisitiria Marigold Seeds (50 seeds)",
"Wisitiria Mint Seeds (100 seeds)",
"Wisitiria Sunflower Seeds (50 seeds)",
"Wisitiria Seeds Cherry Tomato Seeds (100 seeds)",
"Red Lettuce Seeds (10 seeds)",
"Vermi Compost (2kg, Buy 1 Get 1 free)",
"Ornamental Chilli Seeds (10 Seeds)",
"Chilli Jalapeno Seeds (10 Seeds)",
"Vintage Seed Gift Bottles (Return Gift) (1pc)",
"Wooden Tongue Cleaner (1pc)",
"Demand Agro Pumpkin F1 Das (Zucchini) Seeds",
"Microgreen Spinach Seeds (10 gms)",
"Microgreen Flax Seeds (10 gms)",
"Microgreen Fenugreek Seed (10 gms)",
"Miniature Snails for Fairy Gardens",
"Wooden Pot Stickers",
"Zucchini Yellow Seeds (4 seeds)",
"Demand Agro Zucuni F1 Yellow Wonder Seeds",
"Water Spray Gun (Fus Fus)",
"Coir Coins (1 Coin)",
"Seeds Card (Happy Birthday)",
"Seeds Card (Thank You)",
"Wisitiria Lotus Seeds (30 seeds)",
"Wisitiria Asparagus Seeds (60 seeds)",
"Wisitiria Carnation Seeds (250 seeds)",
"Watering Spikes for Plants (1pc)",
"Wisitiria Chrysanthemum Seeds (200 seeds)",
"Assorted Microgreens Seeds Pack (1Pack)",
"Wisitiria Dahlia Seeds (100 seeds)",
"Summer Veggies Pack (1Pack)",
"Wisitiria Seeds Ghost Pepper Seeds (30 seeds)",
"Summer Flowers Pack (1Pack)",
"Wisitiria Lavender Seeds (100 seeds)",
"Moss Stick 2 feet",
"Wisitiria Seeds Lettuce Seeds (50 seeds)",
"Ridge Gourd Seeds (5 Seeds)",
"Wisitiria Morning Glory Seeds (100 seeds)",
"Snake Gourd Seeds (5 Seeds)",
"Wisitiria Oregano Seeds (100 seeds)",
"Wisitiria Thyme Seeds (50 seeds)",
"Demand Agro Turnip F1 Purple Top Seeds",
"Sustainable Lifestyle Pack (1Pack)",
"Demand Agro Sage Seeds",
"Demand Agro Basil Purple Seeds",
"Creeper Clips (1pc)",
"Zip tie for creepers 10 inch long (2pcs)",
"Bamboo Straw Cleaner (Natural Fiber 1 Piece)",
"Bamboo Straw Cleaner (Synthetic Fiber 1 Piece)",
"Omaxe Artichoke Green Globe Seeds (1 KGP)",
"Loofah (1pc)",
"Neem Seeds (3 Seeds)",
"Magic Seaweed (20gms)",
"Neem Cake Powder (250gms)",
"Vermi Compost (500gm, Buy 1 Get 1 free)",
"Coco Peat (500gm, Buy 1 Get 1 free)",
"Chilli Long Green Seeds (20 seeds",
"Coriander Seeds (100 seeds)",
"Lady Finger Seeds (Okra Seeds) (10 seeds)",
"Spinach Seeds (100 seeds)",
"Grow Bags (1pc)",
"Radish Seeds (10 seeds)",
"Chrysanthemum Mixed Seeds (30 seeds)",
"Yellow Marigold Seeds (10 seeds)",
"Germination Kit (1Pack)",
"All Season Veggies Seeds Pack (1 Pack)",
"Amaranth (Thotakura) Seeds (10 Seeds)",
"Anti Hairfall Neem Wooden Comb (1pc)",
"Ashwagandha Seeds (10 seeds)",
"Ayurvedic Immunity Booster Seeds Pack (1 Pack)",
"Basil Black Seeds (20 seeds)",
"Beetroot Seeds (15 seeds)",
"Beginner's Pro Garden Kit (1Kit)",
"Cabbage Seeds (10 seeds)",
"Capsicum Yellow Seeds (10 seeds)",
"Gazania Seeds (20 seeds)",
"Perlite (100 gms)",
"Celosia Plumosa Seeds (20 Seeds)",
"Seedling Tray 4 Holes (1pc)",
"Nastratium Mixed Seeds (3 Seeds)",
"Tithonia Seeds (10 seeds)",
"Sweet William Seeds (10 seeds)",
"Dolichos Seeds (5 seeds)",
"Jute Grow Bags (6x6x6 inch)",
"Lotus Seeds (4 seeds)",
"Vermi Compost (100gms, Buy 1 Get 1 free)",
"Coco Peat (100gm, Buy 1 Get 1 free)",
"Chinese Cabbage Seeds (10 seeds)",
"Helichrysum Seeds (10 seeds)",
"Round Gourd Seeds (5 seeds)",
"Venidium White Seeds (10 seeds)",
"Cineraria Double Mix Seeds (10 seeds)",
"Wooden Spoon (1pc)",
"Gardener's Pizza Seeds Pack (1Pack)",
"Demand Agro Basil Black Indian Seeds",
"Demand Agro Carrot Early Nineteen Seeds",
"Demand Agro Pakchoi F1 Hybrid Seeds",
"Hawan Samagri (100gms)",
"Demand Agro Sunflower Sungold Seeds (5 seeds)",
"Lettuce Iceberg Seeds (10 Seeds)",
"Ghost Pepper Seeds (10 Seeds)",
"Natural Reusable Bamboo Straws (1pc)",
"Ladybug (Ladybird) (1pc)",
"Round Tomato Seeds (15 seed",
"Gardening Pot 10-inch (1pc)",
"Fenugreek (Methi) Seeds (10 seeds)",
"Gongura (Roselle) Seeds (10 seeds)",
"Gift cards",
"Biocarve African Marigold F2 Orange Seeds (50 seeds)",
"Biocarve African Marigold F2 Yellow Seeds (50 seeds)",
"Biocarve Basil Green Seeds (50 seeds)",
"Biocarve Broccoli Seeds",
"Biocarve Capsicum Red Queen Seeds",
"Biocarve Carrot Red Long Seeds",
"Biocarve Cherry Tomato Seeds",
"Biocarve Dahlia Double Figaro Mixed Seeds (20 seeds)",
"Biocarve Dianthus Baby Doll Mix Seeds (200 seeds)",
"Biocarve Dianthus Sweet William Mix Seeds (100 seeds)",
"Biocarve Field Peas Seeds (30 seeds)",
"Biocarve Gaillardia Aristata Tokajer Seeds (100 seeds)",
"Biocarve Gazania Sunshine Hybrid Mix Seeds (100 seeds)",
"Biocarve Indian Poppy Mix Seeds (200 seeds)",
"Biocarve Petunia NC Star Mix Seeds (200 seeds)",
"Biocarve Petunia Dwarf Mix Seeds (200 seeds)",
"Biocarve Phlox Beauty Mix Seeds (200 seeds)",
"Biocarve Radish White Seeds",
"Biocarve Rosemary Seeds",
"Biocarve Thyme Seeds (50 seeds)",
"Biocarve Vinca Dwarf Mix Seeds (100 seeds)",
"Biocarve Zinnia Dahlia Flowered Mixed Seeds (80 seeds)",
"Biocarve Zucchini Seeds",
"Eucharis Lily Bulb (1pc)",
"Ginger Lily Bulb (1pc)",
"Gladiolus Bulbs (1pc)",
"Lycoris Lily Bulb (1pc)",
"Rain Lily Mixed Bulb (1pc)",
"Rajnigandha Bulb (1pc)",
"Miniature Birds Assorted (1pc)",
"Miniature Cactus Assorted (1pc)",
"Miniature Chinese Feng Shui Monks (1pc)",
"Miniature Cow Assorted (1pc)",
"Miniature Ducks (1pc)",
"Miniature Elephant Assorted (1pc)",
"Miniature Fence Assorted (1pc)",
"Miniature Geese Assorted (1pc)",
"Miniature Hut Assorted (1pc)",
"Miniature I Love You Toys (1pc)",
"Miniature Monks Assorted (1pc)",
"Miniature Mushroom House Assorted (1pc)",
"Miniature Mushrooms for Fairy Gardens (1pc)",
"Miniature Owl Assorted (1pc)",
"Miniature Rabbits Assorted (1pc)",
"Miniature Sheep Assorted (1pc)",
"Miniature Trees Assorted (1pc)",
"Miniature Tree Trunks Assorted (1pc)",
"Miniature Turtle Assorted (1pc)",
"Miniature Windmill Assorted (1pc)",
"Miniature Wooden Post Assorted (1pc)",
"Biocarve Parsley Seeds",
"Demand Agro Basil Green Seeds",
"Bellis Monstrosa Double Mix Seeds (100 seeds)",
"Plantable Rakhi (1pc)",
"Self Watering Bird (1Pc)",
"Celery Seeds (20 seeds)",
"Leca Clay Balls (250gms)",
"Adenium Seeds (3 Seeds)",
"Miniature Boat (1pc)",
"Miniature Dolphin (1pc)",
"Mustard Oil Cake Powder (200gms)",
"Castor Oil Cake Powder (200gms)",
"TFP Pots (Thermoform) (4 inch",
"Miniature Sofa/ Mini Sofa (1pc)",
"Miniature Puppy (1pc)",
"Watering Can with Sprayer 1 liter (1pc)",
"Biocarve African Marigold F2 White (50 seeds)",
"Biocarve Pansy Swiss Giant Mix Seeds (30 seeds)",
"Coir Pots (2 inch)",
"Moss Stick (1ft Single pc)",
"Watering Can 5 liters (1pc)",
"Rose Seeds (5 seeds)",
"Red Soil for Gardening (1kg)",
"Multi Colored Stones (200gms)",
"Rose Mix (250gms)",
"Gardening TFP Pot 8-inch (3pcs)",
"Zucchini Seeds (4 seeds)",
"Demand Agro Pumpkin F1 Das Seeds",
"Microgreen Kasuri Methi Seeds (20gms)",
"Dianthus Splendor Seeds (20 seeds)",
"Omaxe Cosmos Bright Light Mixed (100 Seeds)",
"Wooden Support Sticks for Plants (Buy 1 Get 1 free)",
"Demand Agro Strawberry Seeds",
"Railing Hook Flower Pots",
"Hanging Pots with Hook and Chain (1 Pot)",
"Wood Saw Dust- Organic Natural (100gms)",
"Charcoal Activated Farmer (100gm)",
"Demand Agro Vinca Dwarf Pacifica Mix Seeds (41 seeds)",
"Plantable Seed Balls",
"Coarse River Sand (0.5kg)",
"Tinda Seeds (4 seeds)",
"Floating Tealight Candles",
"Miniature Bird Nest (1pc)",
"Miniature Old Couple Grandparents",
"Miniature Porcupine",
"Miniature Porcupine Long Nose",
"Miniature Boat with Oars(1pc)",
"Miniature Shy Couple (1 Pair)",
"Burger Seeds Pack",
"Miniature Toy Frog",
"Miniature Toy Car",
"Miniature Toy Bed",
"Artificial Lawn Grass (2ft x1ft)",
"Wheat Grass Head Doll",
"Natural Sola Wood for Flowers",
"Miniature Cat Feeder",
"Miniature Toy TV",
"Aparajita Blue Pea Seeds (5 Seeds)",
"Parijat Harsringar Seeds (3 seeds)",
"4 Inch Coir Pot (1pc)",
"Gardening Gloves Free Size (1 Pair)",
"Omaxe Cineraria Seeds (100 seeds)",
"Rooting Hormone (5gms)",
"Kids Gardening Tools",
"Mini Terracota Pots (5cm)",
"Miniature Resin Orange Slice (10pcs)",
"Miniature Resin Flowers (10 pcs)",
"Coir Pot 6 inch (4pcs)",
"DAP (Phosphate) Granules (5gm)",
"Compost Accelerator (15gm)",
"Self Watering Pot 4in (1pc)",
"Hydroponics Net Pot 3-inch (1pc)",
"Metal Bucket Pot (1pc)",
"Miniature Polymer Clay Watermelon (10pcs)",
"Miniature Polymer Clay Lemon (10pcs)",
"Curry Plant Seeds (5 seeds)",
"Miniature Sea Side Watch Light Tower (1pc)",
"Miniature Mini Resin Mushroom",
"Miniature Old Couple Grandparents -2",
"Imported Mixed Ranunculus Bulb (1pc)",
"Imported Mixed Freesia Bulb (1pc)",
"Flowering Hormone Flowers Booster (5gms)",
"Miniature Polymer Clay Grapes (10pcs)",
"Miniature Polymer Clay Smiley (10pcs)",
"Miniature Polymer Clay Green Orange (10pcs)",
"Miniature Polymer Clay Stars (10pcs)",
"Miniature Furry Dog (1pc)",
"Money Plant Sapling (1pc)",
"Miniature Resin House (1pc)",
"Jasmine, Chameli, Mogra Seeds (3 seeds)",
"Areca Palm Saplings (3pcs)",
"Betel Paan Sapling (1pc)",
"Temple Tree Champa Cutting (1pc)",
"Mirchi Meri Green Palm Plant Sapling (1pc)",
"Winter Flowers Pack",
"Garden Plant Cutter Pruner",
"Miniature Polymer Clay Full Watermelon Slice (10pcs)",
"Miniature Polymer Clay Blue Orange (10pcs)",
"Lemon Balm Seeds (10 Seeds)",
"Organic Plant Food Tablet (3 Tablets)",
"Red Sandal Wood Seeds (5 Seeds)",
"Croton Codiaeum Variegatum (Petra) Sapling (1pc)",
"Golden Cypress Plant Sapling (1pc)",
"Natural Bamboo Seeds (10 Seeds)",
"Turmeric Bulb (1pc)",
"Jade Plant Sapling (1pc)",
"Song Of India Plant Sapling (1pc)",
"Golden Thuja Plant Sapling (1pc)",
"Golden Money Plant Sapling (1pc)",
"Hibiscus Plant Sapling (1pc)",
"ZZ Plant Sapling(1Pc)",
"Ficus Safari Plant Sapling (1pc)",
"Bougainvillea Plant Sapling (1pc)",
"Wick Self Watering Pot (1pc)",
"Miniature Polymer Clay SnowFlakes (10pcs)",
"Miniature Polymer Clay Heart Fimo (10pcs)",
"Sphagnum Peat Moss (50gms)",
"Rubber Plant Sapling (1pc)",
"Rare Black ZZ Plant Sapling (1pc)",
"Miniature Toy Gift Box (1pc)",
"Miniature Toy Basket Ball (1pc)",
"Aloe Vera Plant Sapling (1pc)",
"Peace Lily Plant Sapling (1pc)",
"Snake Plant Sapling (1pc)",
"Philodendron Wendlandii Plant Sapling (1pc)",
"Purple Heart Plant Sapling (1pc)",
"Spider Plant Sapling (1pc)",
"Nimbu Croton Plant Sapling (1pc)",
"Alocasia Velvet Black Plant Sapling (1pc)",
"Dieffenbachia Camille Plant Sapling (1pc)",
"Philodendron Golden Plant Sapling (1pc)",
"Desert Rose Adenium Plant Sapling (1pc)",
"Miniature Beer Bottles (1pc)",
"Miniature Dollhouse Pastry (1pc)",
"Miniature Dollhouse Doughnuts (1pc)",
"Miniature Dollhouse Ice Cream (1pc)",
"Miniature Dollhouse Soda Can (1pc)",
"Dwarf Fiddle Leaf Fig Plant Sapling (1pc)",
"Dracaena Golden Milky Plant Sapling (1pc)",
"Laxmi Kamal Haworthia Succulent Plant (1pc)",
"Wandering Jew Plant Sapling (1pc)",
"Demand Agro Radish Round Red Seeds",
"Vermiculite for Gardening (100gms)",
"Crassula Ovata Plant Sapling (1pc)",
"Rheo Oyster Plant Sapling (1pc)",
"Calathea Never Never Plant Sapling (1pc)",
"Aloe White Succulent Plant (1pc)",
"Aglaonema Lipstick Plant Sapling (1pc)",
"Christmas Cactus Plant Sapling (1pc)",
"Anthurium Chocolate Plant Sapling (1pc)",
"Calathea Burle Marx Prayer Plant Sapling (1pc)",
"Pineapple Plant Sapling (1pc)",
"Marble Money Plant Sapling (1pc)",
"Miniature Leather Sofa (1pc)",
"Miniature Teddy Bear (1pc)",
"Earth Star Plant Cryptanthus Sapling (1pc)",
"Ficus Microcarpa Bonsai Plant Sapling (1pc)",
"English Ivy Plant Sapling (1pc)",
"Biocarve Gompherena Choice Mix Seeds (100 seeds)",
"Fairytale Cactus Elongated Sapling (1pc)",
"Monstera Broken Heart Plant Sapling (1pc)",
"Caladium Plant Sapling (1pc)",
"Lucky Bamboo Plant Saplings (3pcs)",
"Aloe Vera Star Indoor Succulent Plant (1pc)",
"Philodendron Oxycardium Golden Plant Sapling (1pc)",
"Philodendron Oxycardium Green Plant Sapling (1pc)",
"Alocasia Amazonica Plant Sapling (1pc)",
"Alocasia Pola Small Leaf Plant Sapling (1pc)",
"Echeveria Succulent Indoor Plant (1pc)",
"Echeveria Mixed Succulent Indoor Plant (1pc)",
"Black Money Plant Sapling (1pc)",
"Coco Peat Soil (2kg, Buy 1 Get 1 free)",
"Moss Rose Plant Sapling (1pc)",
"Areca Palm Seeds (3 Seed)",
"Philodendron Birkin Plant Sapling (1pc)",
"Philodendron Moonshine Plant Sapling (1pc)",
"String of Bananas Plant Sapling (1pc)",
"Arabian Jasmine Plant Sapling (1pc)",
"Peperomia Green Plant Sapling (1pc)",
"Kaner, Nerium Oleander Plant Sapling (1pc)",
"Ixia Mix Variety Flower Bulb (1pc)",
"Tritonia Mix Flower Bulb (1pc)",
"Rose Plant Sapling (1pc)",
"Dendrobium Orchid Plant Sapling (1pc)",
"Homalomena Plant Sapling (1pc)",
"Strawberries Plant Sapling (1pc)",
"Peperomia Watermelon Plant Sapling (1pc)",
"Dragon Fruit Sapling (1pc)",
"Fittonia White Sapling (1pc)",
"Minima Jasmine Summer Sunset Plant Sapling (1pc)",
"Orinithogalum Mix Flower Bulb (1pc)",
"Gerbera Flower Sapling (1pc)",
"Ixora Plant Sapling (1pc)",
"Jasmine Plant Sapling (1pc)",
"Monstera Deliciosa Plant (1pc)",
"Mosquito Repellent Citronella Herbal Sticks (6pc)",
"Wood Pencil (1pc)",
"Transparent Thin Stationary Tape (1pc)",
"Fancy Fish Eraser Combo (1 set)",
"2B Red Eraser (1pc)",
"Curry Leaves Sapling (1pc)",
"Plant Growth Promoter (5 gms for 5 plants)",
"Gardening Pot 3-inch (1pc)",
"Unicorn Mini Pen (1 piece)",
"Mixed Pink Shade Stones Sheet (1 piece)",
"Green Fern Plant Sapling (1pc)",
"Tillandsia Aeranthos Indoor Air Plant (1pc)",
"Tillandsia Lonantha Air Plant Live (1pc)",
"Glow in the dark Elves(1Pc)",
"Demand Agro Tomato F1 Das (101)",
"Red Sparkling Stars for Art and Craft",
"Golden Sparkling Stars for Art and Craft",
"Miniature Polymer Clay Mixed Butterfly (10pcs)",
"Portulaca Plant Sapling (1pc)",
"Tulip Mix Flower Bulb (1pc)",
"Gardening Pot 2-inch (1pc)",
"Fittonia Red Sapling (1pc)",
"Cupcake Stickers (1pc)",
"Multi Colored Paper Clips (5pcs)",
"Wooden Clips (1pc)",
"Golden Heart Sticker (1pc)",
"Silver Flower Sticker (1pc)",
"Fancy Mirror and Sunglasses Eraser (1pc)",
"Fancy Ring Lipstick Eraser (1pc)",
"Fancy Ladies Bag Eraser (1pc)",
"Doraemon Pen (1pc)",
"Unicorn Pencil (1pc)",
"Doraemon pencil (1pc)",
"Barbie Stickers (1pc)",
"Chota Bheem Stickers (1pc)",
"Motu Patlu Stickers (1pc)",
"Coconut Husks (100gm)",
"Fluffy Fern Plant Sapling (1pc)",
"Sustainable Seed bottle gift pack (1Pack)",
"Eco-Friendly Seed ball gift pack (1Pack)",
"Plantable Seed card gift pack (1Pack)",
"Coleus Plant Sapling (1pc)",
"Philodendron Oxycardium Variegated Plant Sapling (1pc)",
"Wall Creeper Plant sapling (1pc)",
"Peperomia Black Plant Sapling (1pc)",
"Syngonium Wendlandii Plant Sapling (1pc)",
"Philodendron Xanadu Plant Sapling (1pc)",
"Crystal Pebbles (6pc)",
"Barrel Cactus Sapling (1pc)",
"Lithops Plant Sapling (1pc)",
"Miniature Santa Claus (1Pc)",
"Miniature Ladder (1Pc)",
"Miniature Basket (1pc)",
"Miniature Christmas Hats (1pc)",
"Miniature Popcorn Bucket (1pc)",
"Miniature Toy Chair (1pc)",
"Miniature Toy Cat (1pc)",
"Miniature Astronaut Flag (1pc)",
"Miniature Astronaut (1pc)",
"Miniature Moon Fairy (1pc)",
"Miniature Pinecone (1pc)",
"Miniature Dollhouse Hamburger (1pc)",
"Miniature Snowmen (1pc)",
"Silver Money Plant Sapling (1pc)",
"Gardening Pot Round 4inch (1pc)",
"Philodendron Oxycordia Micans Plant Sapling (1pc)",
"Peperomia Creeper Plant Sapling (1pc)",
"Monstera Deliciosa Plant Sapling (1pc)",
"Philodendron Red Plant Sapling (1pc)",
"Papaya Plant Sapling (1pc)",
"Banana Plant Sapling (1pc)",
"Peperomia Obtusifolia Variegated Sapling (1pc)",
"Parijat Harsingar Plant Sapling (1pc)",
"Anthurium Red Plant Sapling (1pc)",
"Miniature Groot (1pc)",
"Miniature Mini Dog (1pc)",
"Plant Climbing Clips (1pc)",
"Peperomia Caperata Plant (1pc)",
"Alocasia Silver Dragon Plant Sapling (1pc)",
"Arrow-Shaped Plant Tag (1pc)",
"T-Shaped Garden Labels (1pc)",
"Chrysanthemum Mix Plant Sapling (1pc)",
"Plant Climbing Wall Clips (1pc)",
"Monstera Dragon Tail Plant Sapling (1pc)",
"Vertical Wall Hanging Pots 4inch (1pc)",
"Yellow Nozzle Sprayer Gun (1pc)",
"Metal Plant Support Stakes (3pcs)",
"Aglaonema Snow White Plant Sapling (1pc)",
"Miniature Mini Rabbit (1pc)",
"Alocasia Wenti Plant Sapling (1pc)",
"Lizard Repellent For Home And Plants (30ml)",
"Aglaonema Pink Valentine Plant Sapling (1pc)",
"Philodendron Billietiae Plant Sapling (1pc)",
"Philodendron Black Cardinal Plant Sapling (1pc)",
"7 Pattern Garden Hose Nozzle Water Spray Gun (1pc)",
"Gardenia Ananta Plant Sapling (1pc)",
"Anthurium Pink Plant Sapling (1pc)",
"Indoor Gardening Tools Set (Cultivator, Small Trowel &amp; Gardening Fork) (1pc)",
"Variegated Sansevieria Golden Plant (1pc)",
"Syngonium Pink Plant Sapling (1pc)",
"Philodendron Paraiso Verde Plant Sapling(1pc)",
"Dieffenbachia Green Magic Plant Sapling (1pc)",
"Miniature Glow Duck (1pc)",
"Chamaedorea Elegans Palm Plant Sapling (1pc)",
"Christmas Tree Plant Sapling (1pc)",
"Cotton Ear Cleaning Buds (70pcs)",
"Gardening Vertical Wall Panels (1pc)",
"Bird of Paradise Plant Sapling (1pc)",
"Philodendron Pink Princess Plant Sapling (1pc)",
"Philodendron White Princess Plant Sapling (1pc)",
"Home Garden Vertical Pots Frame (1 Panel x 3 Pots)",
"Oval Self Watering Pots(1Pc)",
"Demand Agro Cherry Tomato F1 Hybrid(1Pc)",
"Gymnocalycium damsii Var. multiproliferum plant (1pc)",
"Pedilanthus Variegated Jurassic Park Plant Sapling(1Pc)",
"Monstera Peru Plant Sapling (1pc)",
"Echinopsis oxygona plant (1pc)",
"Ice Cream Cone Rubber Pencil Eraser(1Pc)",
"Unicorn Donut Rubber Eraser(1Pc)",
"Hat Shape Rubber Pencil Eraser(1Pc)",
"Cinder for Plants(100grams)",
"Multicolor Car Rubber Pencil Eraser(1Pc)",
"Gardening TFP Pot 6 inch(3Pcs)",
"Crossandra Plant Sapling(1Pc)",
"Bleeding Heart Plant Sapling(1pc)",
"Begonia Don Miller Plant Sapling (1pc)",
"Dwarf Snake Plant(1Pc)",
"Saffron Crocus Bulb(1Pc)",
"Zebra Haworthia plant(1Pc)",
"Paddy Husk-Rice Hulls(50grams)",
"Cactus and Succulent Potting Mix(100grams)",
"Gravel Stone Chips(250grams)",
"Cypress Vine Mix Color Flower Seeds(3 seeds)",
"Aloe Bright Star Succulent Plant(1Pc)",
"Philodendron Cherry Red Plant Sapling(1Pc)",
"Sansevieria Bacularis Mikado Plant Sapling (1pc)",
"Song of Jamaica Plant Sapling(1Pc)",
"Philodendron Silver Sword Hastatum Plant Sapling(1Pc)",
"Calla lily Bulb (1pc)",
"Amaryllis lily Mix Bulb(1Pc)",
"Brazilian Lucky Wood Plant (1pc)",
"Wandering Jew Nanouk Plant Sapling(1Pc)",
"Philodendron Brule Marx Plant Sapling (1Pc)",
"Chinese Money Plant Sapling (1Pc)",
"Calathea maranta ornata Plant (1Pc)",
"Haworthia Retusa Star Cactus(1Pc)",
"Philodendron Ring of Fire Plant Sapling (1Pc)",
"Variegated Rubber Plant Sapling(1Pc)",
"Syngonium Confetti Plant Sapling (1pc)",
"Pre-Loved (Old) Gardening Pot 4-inch(1pc)",
"Biocarve Lemon Basil Seeds (50 Seeds)",
"Omaxe F1 Hybrid Red Pearl Queen Seeds (1PC)",
"Omaxe Rucola Cultivated Seeds (1pc)",
"Demand Agro Basil Green Indian Seeds (1PC)",
"Demand Agro Pakchol-F1 Hybrid seeds (1PC)",
"Pedilanthus Jurassic Park Plant Sapling(1Pc)",
"Plumeria pudica Plant Sapling(1Pc)",
"Philodendron Florida Ghost Plant Sapling (1Pc)",
"Miniature Garden Mushroom (1Pc)",
"Miniature Chick(1Pc)",
"Miniature Garden Pig (1Pc)",
"Miniature Resin Mini Frog(1Pc)",
"Miniature Garden Table (1Pc)",
"Miniature Koala(1Pc)",
"Monstera Leaf Keychain(1Pc)",
"Artificial Plant Car Air Vent Clip, Magnet Refrigerator(1Pc)",
"Dandelion Seed Wish Pendant Necklace(1Pc)",
"Miniature Dollhouse Garden Seahorse(1Pc)",
"Miniature Cute Scarf Rabbit(1Pc)",
"Self Watering Heart (1Pc)",
"Gloriosa Lily Bulb(1Pc)",
"Ring of Fire Variegated Plant Sapling (1Pc)",
"Fishbone Cactus Plant Sapling(1Pc)",
"Philodendron Orange Marmalade Plant Sapling(1Pc)",
"Cordyline Brown Plant Sapling (1Pc)",
"Miniature Squirrel(1Pc)",
"Philodendron Atabapoense Plant Sapling(1pc)",
"Red Sandal Wood Plant Sapling(1Pc)",
"Syngonium Variegated Plant Sapling(1pc)",
"Plantation Drive Ticket",
"Silver Snake Plant(1Pc)",
"Brahma Kamal Plant Sapling (1Pc)",
"Philodendron Gloriosum Plant Sapling (1Pc)",
"Stephania Erecta Plant Bulb(1Pc)",
"Potting Mix for Ferns(100grams)",
"Mini Brazilian Lucky wood plant (1pc)",
"Miniature Glow Rabbit(1pc)",
"Miniature Halloween(1pc)",
"Miniature Ghost(1pc)",
"Miniature Mix(1pc)",
"Miniature Bunny(1pc)",
"Miniature Ear Bunny(1pc)",
"Miniature Easter Bunny(1pc)",
"Echeveria Galuca Building Block Toy Plant(1pc)",
"Haworthia Cooperi Building Block Toy Plant(1pc)",
"Portulacaria Afra Building Block Toy Plant(1pc)",
"Haworthia Margaritifera Building Block Toy Plant(1pc)",
"Astrophytum Asterias Building Block Toy Plant(1pc)",
"Demand Agro Lettuce Lollo Rosso (1pc)",
"Miniature Swan(1pc)",
"China Doll Plant Sapling (1Pc)",
"Dwarf Snake Kokedama (1pc)",
"Pink Syngonium Kokedama",
"Golden Money Plant Kokedama",
"Dried Leaves for Compost and Mulch (30 gms)",
"Pink Agloenema Kokedama",
"Dieffenbachia Camille Plant Kokedama",
"Syngonium plant sapling (1pc)",
"Building Block Tournament Ticket",
"Earth Star Kokedama",
"Philodendron Heart Leaf Plant Sapling (1pc)",
"Yellow Lemon Grass Succulent Indoor Plant (1pc)",
"Yellow Green Sedum Succulent Indoor Plant (1pc)",
"Rosemary Plant Sapling (1pc)",
"Ponytail Palm Sapling (1pc)",
"Unicorn pencil (1pc)",
"Fancy Aeroplane Eraser (1pc)",
"Kokedama Workshop Ticket",
"Pink Kalanchoe Succulent Sapling (1pc)",
"Yellow Kalanchoe Succulent Sapling (1pc)",
"N'joy Money Plant Sapling(1pc)",
"Dracaena Gold Dust Plant Sapling(1pc)",
"Umbrella Tree Plant Sapling(1pc)",
"Thumb Knife Cutter (1pc)",
"Pinwheel Flower Plant Sapling(1pc)",
"Biocarve Alpine Strawberry Seeds (50seeds)",
"Marigold Plant Sapling (1pc)",
"Dianthus Plant Sapling (1pc)",
"Pansy Plant Sapling (1pc)",
"Texas Sage Plant Sapling (1pc)",
"Philodendron White Wizard plant sapling (1pc)",
"Clay Soil for Gardening (500g)",
"Variegated Umbrella Tree Plant Sapling (1pc)",
"Azalea Flower Plant Sapling (1pc)",
];

const OfflineSold = () => {
  const navigate = useNavigate();
  const [date, setDate] = useState("");
  const [personName, setPersonName] = useState("");
  const [email, setEmail] = useState("");
  const [productName, setProductName] = useState(null);
  const [productQuantity, setProductQuantity] = useState("");
  const [placeOfSale, setPlaceOfSale] = useState("");
  const [comments, setComments] = useState("");
  const [showSuccessMessage, setShowSuccessMessage] = useState(false);

  const handleCancel = () => navigate("/");

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!date || !personName || !email || !productName || !productQuantity || !placeOfSale || !comments) {
      alert("All fields are required!");
      return;
    }

    const formData = {
      Date: date,
      PersonName: personName,
      Email: email,
      ProductName: productName,
      ProductQuantity: productQuantity,
      PlaceOfSale: placeOfSale,
      Comments: comments,
      type: "sale",
    };

    try {
      await fetch(
        "https://script.google.com/macros/s/AKfycbyKC1mj-zxwkH8BlZldHRs9FrAKIFN5YuycnyC8BWsFETmmV3_HgXDJugapRSYpY2wDXA/exec",
        {
          method: "POST",
          mode: "no-cors",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(formData),
        }
      );

      setShowSuccessMessage(true);
      setTimeout(() => setShowSuccessMessage(false), 1000);

      setDate("");
      setPersonName("");
      setEmail("");
      setProductName(null);
      setProductQuantity("");
      setPlaceOfSale("");
      setComments("");
    } catch (error) {
      console.error("Error:", error);
      alert("Something went wrong.");
    }
  };

  return (
    <div style={{ display: "flex", justifyContent: "center", alignItems: "center", height: "110vh", backgroundColor: "#f5f5f5" }}>
      <div style={{ background: "#fff", padding: "30px", borderRadius: "10px", boxShadow: "0px 4px 10px rgba(0, 0, 0, 0.1)", width: "500px" }}>
        <h2 style={{ textAlign: "center", color: "#333" }}>Offline Sales Details</h2>

        {showSuccessMessage && <div className="success-message">Data saved successfully!</div>}

        <form onSubmit={handleSubmit} style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
          <div className="form-group">
            <label>Date:</label>
            <input type="date" value={date} onChange={(e) => setDate(e.target.value)} required />
          </div>

          <div className="form-group">
            <label>Person Name:</label>
            <input type="text" value={personName} onChange={(e) => setPersonName(e.target.value)} required />
          </div>

          <div className="form-group">
            <label>Email:</label>
            <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required />
          </div>

          <div className="form-group">
            <label>Product Name:</label>
            <Select
              options={productOptions.map((product) => ({ label: product, value: product }))}
              value={productName ? { label: productName, value: productName } : null}
              onChange={(selectedOption) => setProductName(selectedOption.value)}
              isSearchable={true}
              styles={{
                control: (provided) => ({
                  ...provided,
                  height: "40px",
                  overflowY: "auto",
                }),
              }}
            />
          </div>

          <div className="form-group">
            <label>Product Quantity:</label>
            <input type="number" value={productQuantity} onChange={(e) => setProductQuantity(e.target.value)} min="0" required />
          </div>

          <div className="form-group">
            <label>Place of Sale:</label>
            <input type="text" value={placeOfSale} onChange={(e) => setPlaceOfSale(e.target.value)} required />
          </div>

          <div className="form-group">
            <label>Comments:</label>
            <textarea value={comments} onChange={(e) => setComments(e.target.value)} required />
          </div>

          <div style={{ display: "flex", gap: "10px", marginTop: "10px" }}>
            <button
              type="button"
              onClick={handleCancel}
              style={{
                padding: "12px",
                fontWeight: "bold",
                cursor: "pointer",
                background: "gray",
                color: "white",
                border: "none",
                borderRadius: "5px",
                transition: "0.3s",
                flex: 1,
              }}
              onMouseOver={(e) => (e.target.style.background = "#6c757d")}
              onMouseOut={(e) => (e.target.style.background = "gray")}
            >
              Cancel
            </button>

            <button
              type="submit"
              style={{
                padding: "12px",
                fontWeight: "bold",
                cursor: "pointer",
                background: "#28a745",
                color: "white",
                border: "none",
                borderRadius: "5px",
                transition: "0.3s",
                width: "16rem",
              }}
              onMouseOver={(e) => (e.target.style.background = "#218838")}
              onMouseOut={(e) => (e.target.style.background = "#28a745")}
            >
              Submit
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default OfflineSold;
